
allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url =  'https://www.jitpack.io' }
        maven{ url =  'https://maven.google.com' }
    }

    ext {
        buildVersion = property("buildVersion")
        asmVersion = property("asmVersion")
        mixinVersion = property("mixinVersion")
        // for core mod
        gameVersion = property("gameVersion")
    }
}

subprojects {
    if (project.name != "tools") {
        apply plugin: 'java-library'
        apply plugin: "maven-publish"

        group = "com.github.MDTCopper.loader"
        version = buildVersion

        task sourcesJar(type: Jar) {
            from sourceSets.main.allJava
            archiveClassifier.set('sources')
        }

        tasks.withType(Javadoc) {
            options.encoding = 'UTF-8'
            options.locale = 'en_US'
            options.addStringOption('Xdoclint:none', '-quiet')
            options.JFlags = ['-Duser.language=en', '-Duser.country=US']
        }

        task javadocJar(type: Jar) {
            archiveClassifier.set('javadoc')
            from javadoc
        }

        publishing {
            publications {
                mavenJava(MavenPublication) {
                    from components.java
                    artifact sourcesJar
                    artifact javadocJar
                }
            }
        }
    }

    tasks.withType(JavaCompile).tap {
        configureEach {
            options.encoding = 'UTF-8'
            options.compilerArgs += ['-Xlint:deprecation']
        }
    }
}
